version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest


handlers:
- url: /articles
  static_dir: articles

- url: /Skeleton
  static_dir: Skeleton

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /.*
  script: designr8.app


